### ISSUE TITLE
Model::newFromBuilder returns object with nested objects instead of arrays

### ISSUE THREAD

**Issue by TimAndreJacobsen** [netflex-sdk/sdk#44]
**Describe the bug**
Model::newFromBuilder returns object with objects in fields image and content.
This is where netflex expects there to be arrays and throws an exception in:
netflex/structures/src/Field
line :91
protected function getBlockField (array $block, Field $field)

**To Reproduce**
1. Search for some entries or pages with:
Search::raw($queryString)->relations(['page', 'entry'])->where('published', true)->limit(100)->get();
2. Feed the entries into Model::newFromBuilder with
$article = (new Article)->newFromBuilder($searchItem)
3. render the content somewhere

**Expected behavior**
Entries fetched with search and put through Model::newFromBuilder should have arrays in the proper places

**Screenshots**
![getBlockField](https://user-images.githubusercontent.com/35067641/99915998-96071680-2d07-11eb-97a9-c23a5a3df47c.png)

**Platform (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - PHP 7.4.3
 - netflex-sdk/sdk v2.0.8

**Additional context**
Encountered building search for karabin site

**Comment by thomas-alrek** [comment]
I am guessing you are using the global Search Facade? You can set it up to fetch as associated arrays instead of objects, that should solve the issue,
